### ISSUE TITLE
How to define SPR hierarchy for COCO dataset

### ISSUE THREAD

**Issue by thancaocuong** [murdockhou/Single-Stage-Multi-person-Pose-Machines#10]
Hi, could you tell me how to define the SPR hierarchy for COCO dataset. I get strucked on defining SPRH for nose and left ear and right ear, left eye and right eye. Thank you.

**Comment by murdockhou** [comment]
In original paper , the author did not define this. But as my opinion,  think center point as the first level. Based on SPR, we can get this chains:
```
center point -> nose -> left eye -> left ear
center point -> nose -> right eye -> right ear
```
I think that is not ok if we use one point in more than one chains.  But the offset between eyes and ears is not so long, which we can say they all  `short offset`. So, I think we can also define chains like this:
```
center point -> nose
center point -> left eye -> left ear
center point -> right eye -> right ear
```
I'm not 100% sure but the author did not open his code so far and I think this chains will work well.

**Comment by thancaocuong** [comment]
I tried the first one and didn't get a good result. Maybe the second will be good. Thank you
