### ISSUE TITLE
Result on COCO dataset

### ISSUE THREAD

**Issue by thancaocuong** [murdockhou/Single-Stage-Multi-person-Pose-Machines#13]
thank you. I tried to reimplement it. But do not obtain desireable result on COCOVal2017. How about your result?

**Comment by lipanpeng** [comment]
I also want to know.

**Comment by thancaocuong** [comment]
@lipanpeng  I did implement in pytorch. And I only can obtain 31mAP on coco dataset with Hrnet backbone.

**Comment by oujieww** [comment]
@thancaocuong can you share your pytorch reimplement one to me? thank you

**Comment by lipanpeng** [comment]
@thancaocuong I got terrible results on my dataset with the code.

**Comment by thancaocuong** [comment]
@lipanpeng @oujieww  I will publish it soon, please wait me.

**Comment by thancaocuong** [comment]
@oujieww  @lipanpeng source code is now public at https://github.com/thancaocuong/pytorch-sspm.git
