### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by leonzgtee** [murdockhou/Single-Stage-Multi-person-Pose-Machines#2]
nice job, have you achieve a desirable result? i mean get a mAP around 0.6. i have tried, but could not achieve a good result.

**Comment by murdockhou** [comment]
@leonzgtee hi, i only train & test on ai-challenger dataset, until now, i get ai-valid dataset kps score 0.281 only just 10 epochs. Maybe its more hard for training on COCO dataset.

**Comment by leonzgtee** [comment]
i have noted that the paper use centorid to represent the object instance instead of its center point. in which way did you implement this, i am curious.

**Comment by murdockhou** [comment]
I'm not 100% percent sure about if center point is equal with centroid, but
just like in "Objects As Points" said, its center point can also be learned
well, so i used object's center point. Maybe it is better way to ask author
to make it clear.

leonzgtee <notifications@github.com> 于2019年10月18日周五 上午8:47写道：

**Comment by leonzgtee** [comment]
thanks, i will send a email to the author to inquire about this.

**Comment by wwu** [comment]
@leonzgtee have you heard back about the centroid?

**Comment by leonzgtee** [comment]
not yet……发自我的iPhone------------------ Original ------------------From: Wallace Wu  <notifications@github.com>Date: Fri,Oct 25,2019 11:49 AMTo: murdockhou/Single-Stage-Multi-person-Pose-Machines <Single-Stage-Multi-person-Pose-Machines@noreply.github.com>Cc: leonzgtee <guotaozhu@163.com>, Mention <mention@noreply.github.com>Subject: Re: [murdockhou/Single-Stage-Multi-person-Pose-Machines] about theresult (#2)@leonzgtee have you heard back about the centroid?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/murdockhou/Single-Stage-Multi-person-Pose-Machines/issues/2?email_source=notifications\u0026email_token=AKYUGMBJM3TBZH3A45Y2ESLQQJUDDA5CNFSM4JBV4BIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECHDBGQ#issuecomment-546189466",
"url": "https://github.com/murdockhou/Single-Stage-Multi-person-Pose-Machines/issues/2?email_source=notifications\u0026email_token=AKYUGMBJM3TBZH3A45Y2ESLQQJUDDA5CNFSM4JBV4BIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECHDBGQ#issuecomment-546189466",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thancaocuong** [comment]
@wwu  the author told me that he uses average of all visible keypoints as root joint.

**Comment by wwu** [comment]
> @wwu the author told me that he uses average of all visible keypoints as root joint.

Thank you!
