### ISSUE TITLE
未标记关节点处理

### ISSUE THREAD

**Issue by wwu** [murdockhou/Single-Stage-Multi-person-Pose-Machines#3]
你好, 
训练代码目前没有处理未标记关节点(x=0, y=0, v=3), 请问这个对模型结果会有影响么? 为什么不尝试推断关节的可见状态, 比如将v的状态embedd一起训练?

**Comment by murdockhou** [comment]
你好，(x=0, y=0, v=3)这种情况很少见，不会对模型结果有什么影响。关于推断关键点的可见状态，没有接触过，有什么比较好的参考文献可以提供下吗？

Wallace Wu <notifications@github.com> 于2019年10月18日周五 下午4:46写道：

**Comment by wwu** [comment]
多谢回复. 简单跑了下aichallenger里面的v=3的数据还挺多的. 
paper之前也没留意这方面如何处理, 估计得再看一遍.

另外在测试训练好的模型时候,经常一个视频两帧图片, 其中一帧root joint识别不到, 导致整个人和关节都没有识别的情况, 不知道你有没有碰到过?

**Comment by wwu** [comment]
多谢回复. 简单跑了下aichallenger里面的v=3的数据还挺多的. 
paper之前也没留意这方面如何处理, 估计得再看一遍.

另外在测试训练好的模型时候,经常一个视频两帧图片, 其中一帧root joint识别不到, 导致整个人和关节都没有识别的情况, 不知道你有没有碰到过?

**Comment by murdockhou** [comment]
v=3是比较多，但同时满足x=0, y=0, v=3情况应该很少吧？
我也遇到过，测试的时候偶尔检测不到root joint，并且对于图像中稍微小点的人检测效果就不那么理想，不过这也是bottom-up方法的通病。
话说对分布式训练有兴趣没，搞了几天了，老是有问题。

Wallace Wu <notifications@github.com> 于2019年10月25日周五 上午11:47写道：

**Comment by wwu** [comment]
1 我对tf2.0不是很熟, 分布式的话搞过pytorch, 如果那边需要帮忙的话很乐意.

2 之前单gpu训练发现瓶颈在cpu处理图片和生成label上面, 是不是可以改进一下? 比如提前生成好augment数据, 再直接load 训练? 

3 小人物的情况, hourglass不就是为了解决这个问题的么? 是不是训练集里面小人物的数据不够?

**Comment by murdockhou** [comment]
多谢帮助。
1. tf 2.0分布式搞定了，是自己写的代码有问题
2. 提前生成label会占用很多磁盘空间，这个看取舍了，我个人比较喜欢线上处理，这样在不同的机器上训练会比较方便
3.
ai-challenger中的人体确实都比较大，和coco的相比场景复杂度也简单很多，只不过两者label不一致，有在考虑只训练body点忽略头部点，这样coco和ai-challenger的数据都可以统一起来

Wallace Wu <notifications@github.com> 于2019年11月1日周五 上午11:53写道：

**Comment by wwu** [comment]
3 coco label 头部点可以用鼻子代替么? 或者直接计算一个头部的centroid point

**Comment by murdockhou** [comment]
都可以啊,只要保证生成的label正确就行

Wallace Wu <notifications@github.com> 于2019年11月6日周三 下午12:45写道：
