### ISSUE TITLE
How does the model handle invisible joints and missing root joint?

### ISSUE THREAD

**Issue by PacteraKun** [murdockhou/Single-Stage-Multi-person-Pose-Machines#4]
Great implementation. Thanks. 

I have questions about how the model handles those invisible joints in some images. And also, you can only see partial person in some images, and maybe there isn't any root joint to find for such person. What will the model do? Thanks.

**Comment by murdockhou** [comment]
@PacteraKun ,  I just treat the center point (just the center of one person's box) as root joint of one person, so there is always has root joint if one person can been seen in image. Ignore its completeness. I dose not 100% sure if I am right or not, but the author didn't make clear whcih root joint is, so if you have interest with it, you can email to the author and make root joint clear.
