### ISSUE TITLE
about draw_ttfnet_gaussian function

### ISSUE THREAD

**Issue by thancaocuong** [murdockhou/Single-Stage-Multi-person-Pose-Machines#7]
Hi, I'm very confused about this function. Can you tell me about formular of this function? thank you

**Comment by murdockhou** [comment]
@thancaocuong , It's a way to create gaussian heatmap, refer this [paper](https://arxiv.org/abs/1909.00700), you can find more detail info in **Gaussian Kernels for Training** part.

**Comment by thancaocuong** [comment]
Thank you @murdockhou
