### ISSUE TITLE
About some parameters in gaussian maps

### ISSUE THREAD

**Issue by thancaocuong** [murdockhou/Single-Stage-Multi-person-Pose-Machines#8]
hi, i dont know some parameters such as th (you choose 4.6052) , sigma = 2 when you calculate  x0, y0, x1, y1 (in function create_dense_displacement_map()) 
`def create_dense_displacement_map(self, index, start_joint, end_joint, sigmax=2, sigmay=2):

        # print('start joint {} -> end joint {}'.format(start_joint, end_joint))
        center_x, center_y = int(start_joint[0]), int(start_joint[1])
        th = 4.6052
        delta = np.sqrt(th * 2)

        x0 = int(max(0, center_x - delta * sigmax + 0.5))
        y0 = int(max(0, center_y - delta * sigmay + 0.5))

        x1 = int(min(self.width, center_x + delta * sigmax + 0.5))
        y1 = int(min(self.height, center_y + delta * sigmay + 0.5))

        # x0 = int(clip(start_joint[0], 0, self.width))
        # y0 = int(clip(start_joint[1], 0, self.height))
        # x1 = int(clip(x0+taux, 0, self.width))
        # y1 = int(clip(y0+tauy, 0, self.height))
        # print (x0,x1, y0,y1)
        for x in range(x0, x1):
            for y in range(y0, y1):
                x_offset = (end_joint[0] - x) / self.Z
                y_offset = (end_joint[1] - y) / self.Z
                # print (x_offset, y_offset)
                self.kps_map[y, x, 2*index] += x_offset
                self.kps_map[y, x, 2*index+1] += y_offset
                self.kps_map_weight[y, x, 2*index:2*index+2] = 1.
                if end_joint[0] != x or end_joint[1] != y:
                    self.kps_count[y, x, 2*index:2*index+2] += 1`
how did you define x0, y0, x1, y1? please tell me, I'm so confused about it. Thank you

**Comment by murdockhou** [comment]
@thancaocuong hi, I just choose a gaussian radius as same as draw_gaussian_heatmap. The number of `th` is we always choose in `keypoint heatmap task`. I did not really know clearly why it is but other repo is always choose like that.

**Comment by thancaocuong** [comment]
@murdockhou  thank you, maybe it's hyper parameter.
